const universityTypes = {
  GET_ALL_UNIVERSITY: 'GET_ALL_UNIVERSITY',
  SET_LIST_UNIVERSITY: 'SET_LIST_UNIVERSITY',
  GET_UNIVERSITY_BY_NAME: 'GET_UNIVERSITY_BY_NAME'
};

export default universityTypes;
